# Generated by Django 3.2.9 on 2021-11-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('data_analyzer_nlp1', models.TextField()),
                ('data_analyzer_nlp2', models.TextField()),
                ('data_analyzer_nlp3', models.TextField()),
                ('data_analyzer_nlp4', models.TextField()),
                ('data_analyzer_nlp5', models.TextField()),
            ],
        ),
    ]
